import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import {
  Card,
  SectionTitle,
  StatCard,
  Badge,
  DataTable,
  Loading,
  ErrorState,
} from "@/components/superadmin/kit";

export const Route = createFileRoute("/superadmin/revenue")({
  head: () => ({
    meta: [
      { title: "Revenue & Analytics · Super Admin · Global Prime" },
      { name: "description", content: "Platform revenue, administrator shares, and offerwall performance reports." },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: RevenueAnalytics,
});

function RevenueAnalytics() {
  const { data: stats, isLoading, error } = useQuery({
    queryKey: ["sa", "revenue-analytics"],
    queryFn: async () => {
      // 1. Fetch all offerwalls revenue
      const { data: offerwalls, error: owError } = await supabase
        .from("offerwalls")
        .select("display_name, category, active, revenue");
      if (owError) throw new Error(owError.message);

      // 2. Fetch admins list
      const { data: admins, error: adminError } = await supabase
        .from("admins")
        .select("name, email, role_key, revenue_share, created_at");
      if (adminError) throw new Error(adminError.message);

      // 3. Fetch approved withdrawals
      const { data: withdrawals, error: wdError } = await supabase
        .from("withdrawals")
        .select("amount")
        .eq("status", "approved");
      if (wdError) throw new Error(wdError.message);

      // 4. Calculate stats
      const totalOfferwallRev = (offerwalls ?? []).reduce((a, x) => a + Number(x.revenue ?? 0), 0);
      const totalPaidOut = (withdrawals ?? []).reduce((a, x) => a + Number(x.amount ?? 0), 0);

      // Mock month/day values if not tracking time-series lead records directly in postback_logs table
      // Let's query postback_logs count to show volume of conversions
      const { count: pbCount } = await supabase.from("postback_logs").select("*", { count: "exact", head: true });

      return {
        offerwalls: offerwalls ?? [],
        admins: admins ?? [],
        totalRevenue: totalOfferwallRev,
        totalPaidOut: totalPaidOut,
        conversionsCount: pbCount ?? 0,
      };
    },
  });

  if (isLoading || !stats) return <Loading />;
  if (error) return <ErrorState error={error} />;

  const formatMoney = (v: number) => `$${Number(v).toFixed(2)}`;

  return (
    <div className="space-y-4">
      {/* Revenue Stats Grid */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Total Revenue"
          value={formatMoney(stats.totalRevenue)}
          accent="var(--sa-green)"
        />
        <StatCard
          label="Total Paid Out"
          value={formatMoney(stats.totalPaidOut)}
          accent="var(--sa-red)"
        />
        <StatCard
          label="Net Platform Margin"
          value={formatMoney(Math.max(0, stats.totalRevenue - stats.totalPaidOut))}
          accent="var(--sa-blue)"
        />
        <StatCard
          label="Total Conversions"
          value={stats.conversionsCount.toLocaleString()}
          accent="var(--sa-purple)"
        />
      </div>

      {/* Revenue by Offerwall Table */}
      <Card>
        <SectionTitle>Revenue by Offerwall</SectionTitle>
        <p className="mb-3 text-xs text-[var(--sa-muted)]">
          Lifetime revenue and transaction performance generated by configured third-party offerwalls.
        </p>
        <DataTable
          rows={stats.offerwalls}
          exportName="revenue_by_offerwall"
          columns={[
            { key: "display_name", header: "Offerwall" },
            { key: "category", header: "Category" },
            {
              key: "revenue",
              header: "Total Revenue",
              render: (r) => <span className="font-bold text-emerald-400">{formatMoney(Number(r.revenue ?? 0))}</span>,
            },
            {
              key: "active",
              header: "Status",
              render: (r) => (
                <Badge tone={r.active ? "green" : "red"}>
                  {r.active ? "active" : "disabled"}
                </Badge>
              ),
            },
          ]}
        />
      </Card>

      {/* Revenue by Admin Table */}
      <Card>
        <SectionTitle>Revenue Shares by Administrator</SectionTitle>
        <p className="mb-3 text-xs text-[var(--sa-muted)]">
          Registered admin accounts, assigned roles, and configured revenue share percentages.
        </p>
        <DataTable
          rows={stats.admins}
          exportName="revenue_by_admin"
          columns={[
            { key: "name", header: "Admin Name" },
            { key: "email", header: "Email Address" },
            {
              key: "role_key",
              header: "Role Group",
              render: (r) => <Badge tone="purple">{r.role_key}</Badge>,
            },
            {
              key: "revenue_share",
              header: "Rev Share %",
              render: (r) => <span className="font-mono">{r.revenue_share}%</span>,
            },
          ]}
        />
      </Card>
    </div>
  );
}
